### ISSUE TITLE
For statements

### ISSUE THREAD

**Issue by felixdivo** [dsvictor94/vscode-promela#1]
[For statements](http://spinroot.com/spin/Man/for.html) are not recognized.

**Comment by dsvictor94** [comment]
Thank you! I add suport to it and relase the version 0.3.0

**Comment by dsvictor94** [comment]
I try run exemple program available in the for documentation link, but none of them runs in spin last version
how you are running yours models?

**Comment by felixdivo** [comment]
I run them using [ispin](http://spinroot.com/spin/Man/3_SpinGUI.html) and edit them in VS Code. This is not exactly convenient but works for the few tasks in my University course.

**Comment by dsvictor94** [comment]
You can provide some exemple?
I try run the follow code with ispin
```
1	int i;
2	
3	for (i : 1 .. 10) {
4	    printf("i = %d\n", i)
5	}
````
but fails with `spin: ex.2.pml:3, Error: syntax error	saw '289' near 'for'`

**Comment by dsvictor94** [comment]
And if wanna try, this extension provide a debugger extension too.
I do not document it on readme because it's not stable enough, but it can be a complement to ispin at least to debug step by step

**Comment by felixdivo** [comment]
Oh, nice to know about the debugger. Your file does not run at my installation either. I seems like `for` statements are not allowed in the main part of the program. But wrapping it in an init block worked:

```
init {
    int i;
    for (i : 1 .. 10) {
        printf("i = %d\n", i)
    }
}
```
